#服务器初始化
# 1 初始化服务器系统，包括内核参数，打开文件数，防火墙等内容
yum -y update

# disable selinux 
sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
setenforce 0

cat << 'EOF' >> /etc/bashrc
export HISTFILE=/var/log/.history_log
export HISTSIZE=5000
export HISTTIMEFORMAT="%Y-%m-%d %H:%M:%S `who am i | awk '{print $1,$5}'` "
export HISTCONTROL=ignoredups 
EOF

source /etc/bashrc

# sys kernel conf
cat << 'EOF' > /etc/sysctl.conf 
vm.swappiness = 0
kernel.sysrq = 1
net.ipv4.neigh.default.gc_stale_time = 120
net.ipv4.conf.all.rp_filter = 0
net.ipv4.conf.default.rp_filter = 0
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.lo.arp_announce = 2
net.ipv4.conf.all.arp_announce = 2
#net.ipv4.tcp_max_tw_buckets = 5000
#net.ipv4.tcp_syncookies = 1
#net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv4.tcp_slow_start_after_idle = 0
#fs.file-max = 999999
#net.ipv4.tcp_tw_reuse = 1
#net.ipv4.tcp_keepalive_time = 600
#net.ipv4.tcp_fin_timeout = 30
net.ipv4.tcp_max_tw_buckets = 5000
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.tcp_rmem = 10240 87380 12582912
net.ipv4.tcp_wmem = 10240 87380 12582912
net.core.netdev_max_backlog = 8096
net.core.rmem_default = 6291456
net.core.wmem_default = 6291456
net.core.rmem_max = 12582912
net.core.wmem_max = 12582912
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 8192
net.ipv4.tcp_tw_recycle = 1
#net.core.somaxconn=262114
net.core.somaxconn=65535
net.ipv4.tcp_max_orphans=262114
fs.file-max = 999999
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_fin_timeout = 30
vm.overcommit_memory = 1
EOF

sysctl -p

cat  << 'EOF' >> /etc/security/limits.conf 
root soft nofile 65535
root hard nofile 65535
* soft nofile 65535
* hard nofile 65535
EOF

# iptables set 根据实际情况进行修改内容
cat << 'EOF' >> /tmp/iptables.sh
# Generated by iptables-save v1.4.21 on Wed Mar  9 01:24:34 2022
*nat
:PREROUTING ACCEPT [173982282:10932693150]
:INPUT ACCEPT [173982228:10932689718]
:OUTPUT ACCEPT [2930922:232600743]
:POSTROUTING ACCEPT [2930922:232600743]
COMMIT
# Completed on Wed Mar  9 01:24:34 2022
# Generated by iptables-save v1.4.21 on Wed Mar  9 01:24:34 2022
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [888775673:393395007768]
:l - [0:0]
-A INPUT -s 18.162.207.78/32 -p tcp -m multiport --dports 9100 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 49.0.255.217/32 -p tcp -m tcp --dport 8080 -j ACCEPT
-A INPUT -s 14.17.114.128/32 -p tcp -m tcp --dport 8443 -j ACCEPT
-A INPUT -s 45.207.36.66/32 -p tcp -m multiport --dports 9100 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 45.207.36.63/32 -p tcp -m multiport --dports 9100 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 45.207.36.60/32 -p tcp -m multiport --dports 9100 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j REJECT --reject-with icmp-port-unreachable
-A INPUT -p tcp -m multiport --dports 22,80,443 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 127.0.0.1/32 -d 127.0.0.1/32 -j ACCEPT
-A INPUT -p udp -m udp --sport 53 -j ACCEPT
-A INPUT -p udp -m udp --dport 53 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -j DROP
COMMIT
# Completed on Wed Mar  9 01:24:34 2022
EOF
iptables-restore /tmp/iptables.sh

# 2. 安装java redis mysql 等软件环境

# javac 与java的区别 原创
# java编译器名称是javac,是将源文件编译为字节码文件的程序,而java是java解释器的名称,也就是解释和执行字节码文件的程序。 运行javac命令后,如果成功编译没有错误的话,会出现一个HelloWorld.class的文件。
# 2.1 安装java 
# 安装jdk
yum install java-17-openjdk-devel 
# 安装jre 
yum install java-17-openjdk 
# 测试 java 
java -version

# 2.2 安装redis 
cd /opt/


 # ubuntu  依赖 "sudo apt install build-essential tcl"

wget https://download.redis.io/redis-stable.tar.gz
tar -xzvf redis-stable.tar.gz
cd redis-stable
make

#To install these binaries in /usr/local/bin, run:
make install

redis-server
# 配置配置文件，利用redis-server 启动。

# 2.3 install mysql use rpm 
# 设置 mysql yum 源
#
sudo yum localinstall https://dev.mysql.com/get/mysql80-community-release-el7-7.noarch.rpm
#
# 安装 软件 包
sudo yum --enablerepo=mysql80-community install mysql-community-server
# To install MySQL 5.7, you need to disable mysql80-community repository then download it. 如果安装5.7 请禁用8.0的包
sudo yum --disablerepo=mysql80-community --enablerepo=mysql57-community install mysql-community-server
#
sudo systemctl enable  --now mysqld.service
#
sudo systemctl restart mysqld.service
# Set MySQL root password
grep 'A temporary password is generated for root@localhost' /var/log/mysqld.log |tail -1
# 
# Change mysql root user password and secure database server installation:
 sudo mysql_secure_installation

# Configure Firewall if Database Server is accessed remotely
# With iptables:
sudo iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 3306 -j ACCEPT
sudo service iptables restartt
# Firewalld:
sudo firewall-cmd --add-service mysql --permanent
sudo firewall-cmd --reload
#Test your settings:
$ mysql -u root -p
# Enter password:
############finished 参考 https://computingforgeeks.com/installing-mysql-server-on-centos-rhel/?expand_article=1

# 安装openresty 软件，参考文档

# 部署java 服务，参考supervisord 进行管理java 

# 后端服务：
cat << 'EOF' >> /etc/supervisord.d/admin-java.ini 
[program:admin]
command=/usr/bin/java -Xms2g -Xmx4g -jar /data/admin/dayitong-admin.jar
directory=/data/admin/
stdout_logfile=/data/admin/java-admin.log
autostart=true
autorestart=true
redirect_stderr=true
user=root
startsecs=0
EOF 
# 前端服务：
cat << 'EOF' >>  /etc/supervisord.d/front-java.ini 
[program:front]
command=/usr/bin/java -Xms2g -Xmx4g -jar /data/front/dayitong-front.jar
directory=/data/front/
stdout_logfile=/data/front/java-front.log
autostart=true
autorestart=true
redirect_stderr=true
user=root
startsecs=0
EOF

supervisorctl relaod
supervisorctl status 
supervisorctl start all 

# 重启服务 
# 前端
supervisorctl restart front
# 重启后端
supervisorctl restart admin
# 设置手机



# nohup 运营方式

nohup java -Xms2g -Xmx4g -jar dayitong-admin.jar >> admin.out  2>&1 &

