apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-ebs-pv
  labels:
    type: aws-ebs
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: "<volume-id>"
    fsType: ext4
