apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-nfs-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    path: /usr/local/path
    server: nfs-server-ip
