apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: devops-test
spec:
  storageClassName: storageclass1
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi