apiVersion: v1
kind: ConfigMap
metadata:
  name: mvn-settings
  labels:
    app: jenkins-server
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
      <localRepository>/var/jenkins_home/repository</localRepository>
      <interactiveMode>true</interactiveMode>
      <offline>false</offline>
      <pluginGroups>
        <pluginGroup>org.sonarsource.scanner.maven</pluginGroup>
      </pluginGroups>
      <profiles>
        <profile>
            <id>sonar</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
            <properties>
                <!-- Optional URL to server .default value is http://localhost:9000-->
                <sonar.host.url>http://sonarqube:9000</sonar.host.url>
            </properties>
        </profile>
      </profiles>
    </settings>